added --help, lack of --sleep now causes one-shot mode, & relicensed because I don

diff --git a/rnd-bg b/rnd-bg
--- a/rnd-bg
+++ b/rnd-bg
@@ -1,26 +1,8 @@
 #!/bin/bash
-# wallpaper shuffler and image-resizer
-#=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~==~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~#
-# Copyright (C) 2017 Brianna Rainey
-# This file is part of Wallpaper Manager
-#
-# Wallpaper Manager is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program, in a file named "COPYING".  If not, see
-# <http://www.gnu.org/licenses/>
-#
+# wallpaper shuffler and image-resizer script
 #=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~==~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~#
 # by tassaron on march 5 2017
-# last updated may 4 2017
+# updated 2017-05-04, 2018-09-21
 #
 #=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~==~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~#
 
@@ -48,11 +30,10 @@ if ! [ -d "$WALLPAPER_DIR" ]; then
 fi
 
 # OPTIONS - change these to set default behaviour
-SLEEP_TIME=30s
+SLEEP_TIME=x
 RESOLUTION=1366x768
 VERBOSE=0
 WATERMARK=0
-
 
 # FUNCTIONS
 create_resized_img() {
@@ -99,21 +80,30 @@ set_new_bg () {
             create_resized_img "$new_img" "${WALLPAPER_DIR}/resized/$(basename ${new_img})"
         fi
         hsetroot -center "${WALLPAPER_DIR}/resized/$(basename ${new_img})"
+        if [ "$?" -ne 0 ]; then
+            echo 'Error encountered by hsetroot'
+        fi
     fi
+}
+
+print_help () {
+    echo "usage: rnd-bg [--help] [--kill] [--verbose] [--watermark] [--sleep] XmXs [--res] 1366x768"
 }
 
 # MAIN
 # set options
+active=1
 getting_sleep=0
 getting_res=0
 for argument; do
     if [ "$getting_sleep" = 1 ]; then SLEEP_TIME="$argument"; getting_sleep=0; continue; fi
     if [ "$getting_res" = 1 ]; then RESOLUTION="$argument"; getting_res=0; continue; fi
-    if [ "$argument" = "-kill" ]; then killall rnd-bg; fi
-    if [ "$argument" = "-v" ]; then VERBOSE=1; fi
-    if [ "$argument" = "-watermark" ]; then WATERMARK=1; fi
-    if [ "$argument" = "-sleep" ]; then getting_sleep=1; fi
-    if [ "$argument" = "-res" ]; then getting_res=1; fi
+    if [ "$argument" = "-h" ] || [ "$argument" = "--help" ]; then print_help; active=0; break; fi
+    if [ "$argument" = "-k" ] || [ "$argument" = "--kill" ]; then killall rnd-bg; fi
+    if [ "$argument" = "-v" ] || [ "$argument" = "--verbose" ]; then VERBOSE=1; fi
+    if [ "$argument" = "-w" ] || [ "$argument" = "--watermark" ]; then WATERMARK=1; fi
+    if [ "$argument" = "-s" ] || [ "$argument" = "--sleep" ]; then getting_sleep=1; fi
+    if [ "$argument" = "-r" ] || [ "$argument" = "--res" ]; then getting_res=1; fi
 done
 # create directories if they don't exist
 if [ ! -d "${WALLPAPER_DIR}/watermark" ]; then
@@ -123,7 +113,8 @@ if [ ! -d "${WALLPAPER_DIR}/resized" ]; then
     mkdir "${WALLPAPER_DIR}/resized"
 fi
 # loop
-while true; do
+while [ "$active" = 1 ]; do
     set_new_bg
+    if [ "$SLEEP_TIME" = "x" ]; then break; fi
     sleep $SLEEP_TIME
 done
